[package]
name = "byondapi-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["515.1609"]
"515.1609" = []

[build-dependencies]
bindgen = "0.66.1"
reqwest = { version = "0.11.18", features = ["blocking"] }
tempfile = "3.6.0"
walkdir = "2.3.3"
zip = "0.6.6"
